import localFont from "next/font/local";
import "./globals.css";
import { Outfit, Poppins } from "next/font/google"
import Provider from "./provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit = Outfit({subsets:['latin']})
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={outfit.className}
      >
        <Provider>
        {children}
        </Provider>
      </body>
    </html>
  );
}
